In [1]:
import NaiveBayes as nb
import numpy as np
import pandas as pd
from collections import namedtuple
from sklearn.metrics import confusion_matrix

# Battery

In [2]:
data = pd.DataFrame.from_csv("Modified_Crimes.csv")
train = data[data['Primary Type']=="BATTERY"]
train.head()

Date Primary Type              Description  \
ID                                                                       
10504504  04/30/2016 12:00:00 AM      BATTERY  DOMESTIC BATTERY SIMPLE   
10504538  04/30/2016 12:14:00 AM      BATTERY  DOMESTIC BATTERY SIMPLE   
10504546  04/30/2016 01:15:00 AM      BATTERY  DOMESTIC BATTERY SIMPLE   
10504547  04/30/2016 12:45:00 AM      BATTERY  DOMESTIC BATTERY SIMPLE   
10504553  04/30/2016 12:27:00 AM      BATTERY  DOMESTIC BATTERY SIMPLE   

         Location Description  Arrest  Domestic  Ward  Year  Hour  
ID                                                                 
10504504            RESIDENCE   False      True   6.0  2016     0  
10504538            RESIDENCE    True      True  35.0  2016     0  
10504546            APARTMENT   False     False   7.0  2016     1  
10504547            APARTMENT    True      True  28.0  2016     0  
10504553            APARTMENT   False      True  35.0  2016     0

In [3]:
train = train.rename(columns={"Location Description": "LocationDescription"})
test = train[train['Year']==2017]
train= train[train['Year'] < 2017]

In [5]:
dict_table = {}
target = "Arrest"
features = ['LocationDescription', 'Description', 'Domestic', 'Hour', 'Ward']
# Use np.where(condition) to look for indice
for col_n in features:
    small_table = nb.CreateTable(col_n, train[col_n])
    tr_arr = list(map(lambda x: nb.fillTable(x, train[col_n], train[target], True), train[col_n].unique()))
    fa_arr = list(map(lambda x: nb.fillTable(x, train[col_n], train[target], False), train[col_n].unique()))
    small_table=small_table._replace(true_p=tr_arr)
    small_table=small_table._replace(false_p=fa_arr)
    
    dict_table[col_n] = small_table

In [6]:
answer = list(map(lambda x: nb.CalculateNaiveBayes(dict_table, features, test.loc[x]), test.index))
print("Accuracy: ",len(np.where(test['Arrest']==answer)[0])/len(test))
confusion_matrix(test['Arrest'], answer,labels=[True, False])

Accuracy:  0.6207479161973417


array([[1899, 1715],
       [5019, 9123]])

# CRIMINAL DAMAGE

In [7]:
data = pd.DataFrame.from_csv("Modified_Crimes.csv")
train = data[data['Primary Type']=="CRIMINAL DAMAGE"]
train.head()

Date     Primary Type          Description  \
ID                                                                       
10504542  04/30/2016 12:00:00 AM  CRIMINAL DAMAGE          TO PROPERTY   
10504573  04/30/2016 02:01:00 AM  CRIMINAL DAMAGE  CRIMINAL DEFACEMENT   
10469298  03/31/2016 09:30:00 AM  CRIMINAL DAMAGE           TO VEHICLE   
10504589  04/30/2016 12:05:00 AM  CRIMINAL DAMAGE          TO PROPERTY   
10504590  04/30/2016 12:12:00 AM  CRIMINAL DAMAGE           TO VEHICLE   

                    Location Description  Arrest  Domestic  Ward  Year  Hour  
ID                                                                            
10504542                 APPLIANCE STORE   False     False  30.0  2016     0  
10504573                RESIDENCE-GARAGE    True     False  22.0  2016     2  
10469298  PARKING LOT/GARAGE(NON.RESID.)    True     False  32.0  2016     9  
10504589                       APARTMENT   False     False  24.0  2016     0  
10504590                          STREET   False     False  22.0  2016     0

In [8]:
train = train.rename(columns={"Location Description": "LocationDescription"})
test = train[train['Year']==2017]
train= train[train['Year'] < 2017]

In [9]:
dict_table = {}
target = "Arrest"
features = ['LocationDescription', 'Description', 'Domestic', 'Hour', 'Ward']
# Use np.where(condition) to look for indice
for col_n in features:
    small_table = nb.CreateTable(col_n, train[col_n])
    tr_arr = list(map(lambda x: nb.fillTable(x, train[col_n], train[target], True), train[col_n].unique()))
    fa_arr = list(map(lambda x: nb.fillTable(x, train[col_n], train[target], False), train[col_n].unique()))
    small_table=small_table._replace(true_p=tr_arr)
    small_table=small_table._replace(false_p=fa_arr)
    
    dict_table[col_n] = small_table

In [10]:
answer = list(map(lambda x: nb.CalculateNaiveBayes(dict_table, features, test.loc[x]), test.index))
print("Accuracy: ",len(np.where(test['Arrest']==answer)[0])/len(test))
confusion_matrix(test['Arrest'], answer,labels=[True, False])

Accuracy:  0.6999625187406296


array([[ 381,  247],
       [2955, 7089]])

# NARCOTICS

In [11]:
data = pd.DataFrame.from_csv("Modified_Crimes.csv")
train = data[data['Primary Type']=="NARCOTICS"]
train.head()

Date Primary Type                   Description  \
ID                                                                            
10504512  04/30/2016 12:00:00 AM    NARCOTICS  POSS: CANNABIS 30GMS OR LESS   
10504545  04/30/2016 12:35:00 AM    NARCOTICS  POSSESSION OF DRUG EQUIPMENT   
10495687  04/22/2016 05:34:00 PM    NARCOTICS      ALTER/FORGE PRESCRIPTION   
10504584  04/30/2016 02:52:00 AM    NARCOTICS                 POSS: COCAINE   
10504711  04/30/2016 08:15:00 AM    NARCOTICS  POSS: CANNABIS 30GMS OR LESS   

            Location Description  Arrest  Domestic  Ward  Year  Hour  
ID                                                                    
10504512                SIDEWALK    True     False  29.0  2016     0  
10504545                  STREET    True     False  24.0  2016     0  
10495687              DRUG STORE    True     False   3.0  2016    17  
10504584                  STREET    True     False  30.0  2016     2  
10504711  VEHICLE NON-COMMERCIAL    True     False  35.0  2016     8

In [12]:
train = train.rename(columns={"Location Description": "LocationDescription"})
test = train[train['Year']==2017]
train= train[train['Year'] < 2017]

In [13]:
dict_table = {}
target = "Arrest"
features = ['LocationDescription', 'Description', 'Domestic', 'Hour', 'Ward']
# Use np.where(condition) to look for indice
for col_n in features:
    small_table = nb.CreateTable(col_n, train[col_n])
    tr_arr = list(map(lambda x: nb.fillTable(x, train[col_n], train[target], True), train[col_n].unique()))
    fa_arr = list(map(lambda x: nb.fillTable(x, train[col_n], train[target], False), train[col_n].unique()))
    small_table=small_table._replace(true_p=tr_arr)
    small_table=small_table._replace(false_p=fa_arr)
    
    dict_table[col_n] = small_table

In [14]:
answer = list(map(lambda x: nb.CalculateNaiveBayes(dict_table, features, test.loc[x]), test.index))
print("Accuracy: ",len(np.where(test['Arrest']==answer)[0])/len(test))
confusion_matrix(test['Arrest'], answer,labels=[True, False])

Accuracy:  0.6902216427640157


array([[2647, 1186],
       [   2,    0]])